# Generated by Django 2.0.2 on 2018-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20180313_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
