# Generated by Django 2.0.1 on 2018-03-19 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20180319_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 3, 19, 22, 53, 4, 12967)),
        ),
    ]
