

EDU_CHOICES = (
    ('',''),
    ('High School','High School'),
    ('Associates Degree', 'Associates Degree'),
    ('Community College','Community College'),
    ("Bachelor's Degree", "Bachelor's Degree"),
    ("Master's Degree", "Master's Degree"),
    ('MBA', 'MBA'),
    ('PhD', 'PhD')
)
Skills_choices = (
    ("Java", "Java"),
    ("C", "C"),
    ("Python", "Python"),
    ("C#", "C#"),
    ("Visual Basic .NET", "Visual Basic .NET"),
    ("PHP", "PHP"),
    ("JavaScript", "JavaScript"),
    ("Delphi/Object Pascal", "Delphi/Object Pascal"),
    ("Ruby", "Ruby"),
    ("SQL", "SQL"),
    ("Visual Basic", "Visual Basic"),
    ("PL/SQL", "PL/SQL"),
    ("Assembly language", "Assembly language"),
    ("Swift", "Swift"),
    ("Perl", "Perl"),
    ("Go", "Go"),
    ("MATLAB", "MATLAB"),
    ("Content management", "Content management"),
    ("Data presentation", "Data presentation"),
    ("Database administration", "Database administration"),
    ("Middleware and integration software", "Middleware and integration software"),
    ("Mobile development", "Mobile development"),
    ("Network and information security", "Network and information security"),
    ("Software engineering", "Software engineering"),
    ("Software management", "Storage systems and management"),
    ("Tech support", "Tech support"),
    ("User interface design", "User interface design"),
    ("UI/UX", "UI/UX"),
    ("Web architecture and development framework", "Web architecture and development framework")
)

CITIES_CHOICES = (("New York", "New York"),
    ("Los Angeles", "Los Angeles"),
    ("Chicago", "Chicago"),
    ("Houston", "Houston"),
    ("Philadelphia", "Philadelphia"),
    ("Phoenix", "Phoenix"),
    ("San Antonio", "San Antonio"),
    ("San Diego", "San Diego"),
    ("San Jose", "San Jose"),
    ("Austin", "Austin"),
    ("Jacksonville", "Jacksonville"),
    ("San Francisco", "San Francisco"),
    ("Indianapolis", "Indianapolis"),
    ("Columbus", "Columbus"),
    ("Charlotte", "Charlotte"),
    ("Seattle", "Seattle"),
    ("Denver", "Denver"),
    ("El Paso", "El Paso"),
    ("Detroit", "Detroit"),
    ("Washington	", "Washington	"),
    ("Boston", "Boston"),
    ("Memphis", "Memphis"),
    ("Nashville", "Nashville"),
    ("Portland", "Portland"),
    ("Oklahoma City", "Oklahoma City"),
    ("Las Vegas", "Las Vegas"),
    ("Baltimore", "Baltimore"),
    ("Louisville", "Louisville"),
    ("Milwaukee", "Milwaukee"),
    ("Albuquerque", "Albuquerque"),
    ("Tucson", "Tucson"),
    ("Fresno", "Fresno"),
    ("Sacramento", "Sacramento"),
    ("Kansas City", "Kansas City"),
    ("Long Beach", "Long Beach"),
    ("Mesa", "Mesa"),
    ("Atlanta", "Atlanta"),
    ("Colorado Springs", "Colorado Springs"),
    ("Virginia Beach", "Virginia Beach"),
    ("Raleigh", "Raleigh"),
    ("Omaha", "Omaha"),
    ("Miami", "Miami"),
    ("Oakland", "Oakland"),
    ("Minneapolis", "Minneapolis"),
    ("Tulsa", "Tulsa"),
    ("Wichita", "Wichita"),
    ("New Orleans", "New Orleans")
                  )

MAJOR_CHOICES = (

)