# Generated by Django 2.0.2 on 2018-03-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='2NMR5', max_length=5, primary_key=True, serialize=False),
        ),
    ]
