# Generated by Django 2.0.2 on 2018-03-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0002_auto_20180228_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='X6E2E', max_length=5, primary_key=True, serialize=False),
        ),
    ]
