# Generated by Django 2.0.2 on 2018-03-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0003_auto_20180305_1948'),
        ('offer_solicit', '0003_auto_20180308_1336'),
    ]

    operations = [
    ]
