# Generated by Django 2.0.1 on 2018-03-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0012_auto_20180313_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='HBC5F', max_length=5, primary_key=True, serialize=False),
        ),
    ]
