# Generated by Django 2.0.1 on 2018-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0017_auto_20180313_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='XCNBX', max_length=5, primary_key=True, serialize=False),
        ),
    ]
