# Generated by Django 2.0.1 on 2018-03-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0018_auto_20180316_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='K9EVD', max_length=5, primary_key=True, serialize=False),
        ),
    ]
