# Generated by Django 2.0.1 on 2018-03-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0019_auto_20180317_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='VYYKE', max_length=5, primary_key=True, serialize=False),
        ),
    ]
