# Generated by Django 2.0.1 on 2018-03-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0021_auto_20180317_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='OC2H9', max_length=5, primary_key=True, serialize=False),
        ),
    ]
