# Generated by Django 2.0.1 on 2018-03-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0022_auto_20180318_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='QWZZP', max_length=5, primary_key=True, serialize=False),
        ),
    ]
