# Generated by Django 2.0.2 on 2018-03-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0020_auto_20180318_1332'),
        ('offer_solicit', '0023_auto_20180318_0223'),
    ]

    operations = [
    ]
