# Generated by Django 2.0.2 on 2018-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0024_merge_20180318_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='NFDKH', max_length=5, primary_key=True, serialize=False),
        ),
    ]
