# Generated by Django 2.0.1 on 2018-03-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0025_auto_20180318_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_invitation',
            name='candidate_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offer_invitation',
            name='employer_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='HZTN2', max_length=5, primary_key=True, serialize=False),
        ),
    ]
