# Generated by Django 2.0.1 on 2018-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_solicit', '0026_auto_20180319_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_invitation',
            name='uuid',
            field=models.CharField(default='ESIPP', max_length=5, primary_key=True, serialize=False),
        ),
    ]
