# Generated by Django 2.0.1 on 2018-03-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_recruiter_employer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(null=True, upload_to='recruiter/%Y/%m/%d'),
        ),
    ]
