# Generated by Django 2.0.1 on 2018-03-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20180318_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter/%Y/%m/%d'),
        ),
    ]
