# Generated by Django 2.0.2 on 2018-02-28 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('name_english', models.CharField(max_length=200)),
                ('name_local', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('business_location', models.CharField(choices=[('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago'), ('Houston', 'Houston'), ('Philadelphia', 'Philadelphia'), ('Phoenix', 'Phoenix'), ('San Antonio', 'San Antonio'), ('San Diego', 'San Diego'), ('San Jose', 'San Jose'), ('Austin', 'Austin'), ('Jacksonville', 'Jacksonville'), ('San Francisco', 'San Francisco'), ('Indianapolis', 'Indianapolis'), ('Columbus', 'Columbus'), ('Charlotte', 'Charlotte'), ('Seattle', 'Seattle'), ('Denver', 'Denver'), ('El Paso', 'El Paso'), ('Detroit', 'Detroit'), ('Washington\t', 'Washington\t'), ('Boston', 'Boston'), ('Memphis', 'Memphis'), ('Nashville', 'Nashville'), ('Portland', 'Portland'), ('Oklahoma City', 'Oklahoma City'), ('Las Vegas', 'Las Vegas'), ('Baltimore', 'Baltimore'), ('Louisville', 'Louisville'), ('Milwaukee', 'Milwaukee'), ('Albuquerque', 'Albuquerque'), ('Tucson', 'Tucson'), ('Fresno', 'Fresno'), ('Sacramento', 'Sacramento'), ('Kansas City', 'Kansas City'), ('Long Beach', 'Long Beach'), ('Mesa', 'Mesa'), ('Atlanta', 'Atlanta'), ('Colorado Springs', 'Colorado Springs'), ('Virginia Beach', 'Virginia Beach'), ('Raleigh', 'Raleigh'), ('Omaha', 'Omaha'), ('Miami', 'Miami'), ('Oakland', 'Oakland'), ('Minneapolis', 'Minneapolis'), ('Tulsa', 'Tulsa'), ('Wichita', 'Wichita'), ('New Orleans', 'New Orleans')], max_length=50)),
                ('business_license', models.ImageField(upload_to='employer/%Y/%m/%d')),
                ('business_license_thumb', models.ImageField(blank=True, upload_to='employer/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='employer/%Y/%m/%d')),
                ('thumb', models.ImageField(blank=True, upload_to='employer/%Y/%m/%d')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, choices=[('', ''), ('High School', 'High School'), ('Associates Degree', 'Associates Degree'), ('Community College', 'Community College'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('MBA', 'MBA'), ('PhD', 'PhD')], max_length=25)),
                ('education_major', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.IntegerField(blank=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Employer')),
            ],
        ),
    ]
