# Generated by Django 2.0.1 on 2018-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
