# Generated by Django 2.0.1 on 2018-03-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20180312_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Job_kind',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='weekly_hours',
            field=models.IntegerField(null=True),
        ),
    ]
